version: "3"
server:
  command: "php psr-worker.php"
  relay: pipes
metrics:
  address: 0.0.0.0:2112
  collect:
    games_imported:
      type: counter
      help: "Total count of games imported"
      labels:
        - system
    import_called:
      type: counter
      help: "Times when game import was called"
      labels:
        - path
    import_planned:
      type: counter
      help: "How many times was import pushed into task queue."
      labels:
        - source
    games_synced:
      type: counter
      help: "How many games where synchronized to the Laser Liga."
    control_status:
      type: counter
      help: "How many times were the LMX status API called."
    control_load:
      type: counter
      help: "How many times were the LMX load API called."
    control_start:
      type: counter
      help: "How many times were the LMX start API called."
    control_stop:
      type: counter
      help: "How many times were the LMX stop API called."
    results_printed:
      type: counter
      help: "How many results were printed (each copy is counted)."
      labels:
        - language
        - template
    games_printed:
      type: counter
      help: "How many results were printed."
      labels:
        - language
        - template
    load_time:
      type: gauge
      help: "How much time does it take to load a game (create a 0000.game file and music)."
      labels:
        - system
    load_music_time:
      type: gauge
      help: "How much time does it take to load a selected game music."
      labels:
        - system
    music_time_since_load:
      type: gauge
      help: "How much time does it take to load a selected game music since game load."
      labels:
        - system
    control_time:
      type: gauge
      help: "How much does it take to call the control API."
      labels:
        - action
    reset_called:
      type: counter
      help: "How many times was roadrunner reset called"
      labels:
        - worker
    restart_called:
      type: counter
      help: "How many times was server restart called"
    cron_job_started:
      type: counter
      help: "Amount of started cron jobs"
      labels:
        - job
    cron_job_ok:
      type: counter
      help: "Amount of finished cron jobs"
      labels:
        - job
    cron_job_error:
      type: counter
      help: "Amount of finished cron jobs"
      labels:
        - job
rpc:
  listen: tcp://0.0.0.0:6001
http:
  address: 0.0.0.0:8001
  access_logs: true
  middleware:
    - headers
    - http_metrics
  pool:
#    debug: true
    num_workers: 5
    max_jobs: 5
    max_queue_size: 10
    supervisor:
      max_worker_memory: 512
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
      # Status code to use for successful OPTIONS requests. Default value is 200.
      options_success_status: 200
  fcgi:
    address: tcp://0.0.0.0:9000
jobs:
  num_pollers: 10
  timeout: 120
  pipeline_size: 1000
  pool:
    num_workers: 2
    max_jobs: 5
    supervisor:
      max_worker_memory: 512
  consume: [ "tasks" ]
  pipelines:
    tasks: # RoadRunner queue identifier
      driver: memory    # - Queue driver name
      config:
        priority: 10
        prefetch: 10
file_watch:
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 256
  dir: "./lmx/results"
  regexp: ".*\\.game"
logs:
  encoding: console
  level: debug
  mode: production
#  file_logger_options:
#    log_output: "logs/rr.log"
#    max_size: 10
#    max_age: 24
#    max_backups: 10
#    compress: true