version: "3"
server:
  command: "php psr-worker.php"
  relay: pipes
metrics:
  address: 0.0.0.0:2112
rpc:
  listen: tcp://0.0.0.0:6001
http:
  address: 0.0.0.0:8001
  middleware: [ "gzip", "headers" ]
  pool:
    num_workers: 4
    max_jobs: 50
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
      # Status code to use for successful OPTIONS requests. Default value is 200.
      options_success_status: 200
      # Debugging flag adds additional output to debug server side CORS issues, consider disabling in production.
      debug: true
  fcgi:
    address: tcp://0.0.0.0:9000
jobs: # List of RoadRunner queues that can be processed by
  # the consumer specified in the "server" section.
  consume: [ "tasks" ]
  pool:
    num_workers: 2
    max_jobs: 50
  pipelines:
    tasks: # RoadRunner queue identifier
      driver: memory    # - Queue driver name
      config:
        priority: 10
        prefetch: 10
logs:
  encoding: console
  level: debug
  mode: development