services:
    web:
        restart: always
        build: .
        ports:
            - "1234:80"
            - "9999:9999"
        links:
            - "db"
        depends_on:
            - db
        volumes:
            - lmx:/var/www/html/lmx
            - /mnt/d/Docker/private:/var/www/html/private
    db:
        restart: always
        image: "mariadb:latest"
        ports:
            - "3307:3306"
        environment:
            MARIADB_ROOT_PASSWORD: "super-secret-password"
            MARIADB_DATABASE: "lac"
        volumes:
            - /mnt/d/Docker/mysql:/var/lib/mysql
volumes:
    lmx:
        driver: local
        driver_opts:
            type: cifs
            device: "//192.168.50.3/lasermaxx/shared"
            o: username=xxxx,password=xxxxx,rw,file_mode=0777,dir_mode=0777
