services:
  db:
    restart: unless-stopped
    image: "mariadb:10.6.9"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "laser-arena-control"
      MARIADB_ROOT_PASSWORD: "laser-arena-control"
      MYSQL_DATABASE: "lac"
      MARIADB_DATABASE: "lac"
    volumes:
      - mariadb-dev:/var/lib/mysql
    networks:
      - backend
  redis:
    restart: unless-stopped
    image: eqalpha/keydb:latest
    ports:
      - "6379:6379"
    networks:
      - backend
      - frontend
    volumes:
      - ./docker/redis/data:/data
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      secrets:
        - RT_TOKEN
    working_dir: /var/www/
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www
      - ./fpm/:/etc/php/
      - ./docker/core/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8001:8001"
      - "6001:6001"
      - "2112:2112"
      - "2114:2114"
      - "9999:8080"
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      LAC_VERSION: "dev"
      APP_NAME: "Laser arena control"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: "lac"
      DB_USER: "root"
      DB_PASSWORD: "laser-arena-control"
      FEATURE_EVENT_SERVER: true
      FEATURE_LEAGUE: true
      FEATURE_CONTROL: true
      FEATURE_GATES: false
      FEATURE_TABLES: true
      FEATURE_GROUPS: true
  nginx_exporter:
    restart: unless-stopped
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - 9113:9113
    links:
      - web
    networks:
      - backend
    depends_on:
      - web
    command:
      - -nginx.scrape-uri
      - http://web:80/stub_status
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - php
      - db
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
      - "1935:1935"
    networks:
      - backend
      - frontend
    links:
      - php
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/fastcgi_params.conf:/etc/nginx/fastcgi_params.conf
      - ./docker/nginx/mime-types.conf:/etc/nginx/mime-types.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
  gotenberg:
    restart: unless-stopped
    image: gotenberg/gotenberg:8
    networks:
      - backend
    ports:
      - "3000:3000"
  grafana:
    restart: unless-stopped
    image: grafana/grafana-oss
    ports:
      - "3001:3000"
    links:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend
  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    ports:
      - "9090:9090"
    links:
      - php
    networks:
      - backend
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  mariadb-dev:
  grafana-storage:
  prometheus-storage:
networks:
  backend:
  frontend:
secrets:
  RT_TOKEN:
    environment: RT_TOKEN