services:
  db:
    restart: unless-stopped
    image: "mariadb:10.6.9"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "laser-arena-control"
      MARIADB_ROOT_PASSWORD: "laser-arena-control"
      MYSQL_DATABASE: "lac"
      MARIADB_DATABASE: "lac"
    volumes:
      - mariadb-dev:/var/lib/mysql
    networks:
      - backend
  redis:
    restart: unless-stopped
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - backend
      - frontend
    volumes:
      - /Users/Heroyt/Projects/LaserArenaControl/docker/redis/data:/data
  eventServer:
    restart: unless-stopped
    image: heroyt/lac-event-server:latest
    ports:
      - "9999:8080"
    networks:
      - backend
      - frontend
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_HOST: "redis"
  php:
    restart: unless-stopped
    image: "heroyt/laser-arena-control:dev-roadrunner-latest"
    working_dir: /var/www/
    command:
      - /bin/sh
      - ./startRR.sh
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www
      - ./fpm/:/etc/php/
      - ./docker/core/php.ini:/usr/local/etc/php/php.ini
      - /Users/heroyt/Projects/lsr-packages/:/Users/heroyt/Projects/lsr-packages/
    ports:
      - "6001:6001"
      - "2112:2112"
    networks:
      - backend
    environment:
      APP_NAME: "Laser arena control"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: "lac"
      DB_USER: "root"
      DB_PASSWORD: "laser-arena-control"
      FEATURE_EVENT_SERVER: true
      FEATURE_LEAGUE: true
      FEATURE_CONTROL: false
      FEATURE_GATES: false
      FEATURE_TABLES: true
      FEATURE_GROUPS: true
  web:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
      - db
    ports:
      - "8001:80"
      - "443:443"
      - "1935:1935"
    networks:
      - backend
      - frontend
    links:
      - php
    volumes:
      - /Users/Heroyt/Projects/LaserArenaControl:/var/www
      - /Users/Heroyt/Projects/LaserArenaControl/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/Heroyt/Projects/LaserArenaControl/docker/nginx/fastcgi_params.conf:/etc/nginx/fastcgi_params.conf
      - /Users/Heroyt/Projects/LaserArenaControl/docker/nginx/mime-types.conf:/etc/nginx/mime-types.conf
      - /Users/Heroyt/Projects/LaserArenaControl/docker/nginx/ssl:/etc/nginx/ssl
  gotenberg:
    restart: unless-stopped
    image: gotenberg/gotenberg:8
    networks:
      - backend
    ports:
      - "3000:3000"
  grafana:
    restart: unless-stopped
    image: grafana/grafana-oss
    ports:
      - "3001:3000"
    links:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend
  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    ports:
      - "9090:9090"
    links:
      - php
    networks:
      - backend
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  mariadb-dev:
  grafana-storage:
  prometheus-storage:
networks:
  backend:
  frontend: