services:
    web:
        restart: always
        image: heroyt/laser-arena-control:v0.3.0
        ports:
            - "80:80"
            - "9999:9999"
        links:
            - "db"
            - "cache"
        depends_on:
            - db
            - cache
        volumes:
            - lmx:/var/www/html/lmx
            - /home/vojik/lac/private:/var/www/html/private
            - /home/vojik/lac/logs:/var/www/html/logs
    db:
        restart: always
        image: "mariadb:latest"
        ports:
            - "3307:3306"
        environment:
            MARIADB_ROOT_PASSWORD: "laser-arena-control"
            MARIADB_DATABASE: "lac"
        volumes:
            - /home/vojik/lac/mysql:/var/lib/mysql
    cache:
        restart: always
        image: memcached:alpine
        ports:
            - "11211:11211"
volumes:
    lmx:
        driver: local
        driver_opts:
            type: cifs
            device: "//your.ip/lasermaxx/shared"
            o: username=xxxx,password=xxxxx,rw,file_mode=0777,dir_mode=0777
