version: "3"
services:
  db:
    restart: always
    image: "mariadb:10.6.9"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "laser-arena-control"
      MARIADB_ROOT_PASSWORD: "laser-arena-control"
      MYSQL_DATABASE: "lac"
      MARIADB_DATABASE: "lac"
    volumes:
      - mariadb-dev:/var/lib/mysql
    networks:
      - backend
  redis:
    restart: always
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - backend
      - frontend
    volumes:
      - /Users/Heroyt/Projects/LaserArenaControl/docker/redis/data:/data
  eventServer:
    restart: always
    image: heroyt/lac-event-server:latest
    ports:
      - "9999:8080"
    networks:
      - backend
      - frontend
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_HOST: "redis"
  php:
    restart: always
    image: "heroyt/laser-arena-control:dev-nginx-latest"
    working_dir: /var/www/
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www
      - ./fpm/:/etc/php/
      - ./docker/core/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    environment:
      APP_NAME: "Laser arena control"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: "lac"
      DB_USER: "root"
      DB_PASSWORD: "laser-arena-control"
      FEATURE_EVENT_SERVER: true
      FEATURE_LEAGUE: true
      FEATURE_CONTROL: false
      FEATURE_GATES: false
      FEATURE_TABLES: true
      FEATURE_GROUPS: true
  web:
    restart: always
    image: nginx
    depends_on:
      - php
      - db
    ports:
      - "8001:80"
    networks:
      - backend
      - frontend
    links:
      - php
    volumes:
      - /Users/Heroyt/Projects/LaserArenaControl:/var/www
      - /Users/Heroyt/Projects/LaserArenaControl/docker/nginx:/etc/nginx
  gotenberg:
    restart: always
    image: gotenberg/gotenberg:8
    networks:
      - backend
    ports:
      - "3000:3000"
volumes:
  mariadb-dev:
networks:
  backend:
  frontend: