# my global config
global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets:
          - "php:2112"

  - job_name: nginx
    scrape_timeout: 30s
    scrape_interval: 5m
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ nginx_exporter:9113 ]
        #this address refers to exporter:9113 not web server(when running exporter as a service. in this case its not necessary)