<?php

namespace App\Install;

use App\Core\DB;
use App\Models\Game\GameModes\AbstractMode;
use App\Models\Game\PrintStyle;
use App\Models\Game\PrintTemplate;
use Dibi\Exception;

class Seeder implements InstallInterface
{

	public const GAME_MODES = [
		[
			'id_mode'              => 1,
			'system'               => 'evo5',
			'name'                 => 'Team deathmach',
			'description'          => 'Classic team game.',
			'load_name'            => '1-TEAM-DEATHMACH',
			'type'                 => 'TEAM',
			'public'               => true,
			'mines'                => true,
			'part_win'             => true,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => true,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => true,
			'player_players'       => true,
			'player_players_teams' => true,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => false,
			'team_score'           => true,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => false,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => true,
			'best_deaths_own'      => true,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => true,
		],
		[
			'id_mode'              => 2,
			'system'               => 'evo5',
			'name'                 => 'Deathmach',
			'description'          => 'Classic free for all game.',
			'load_name'            => '2-SOLO-DEATHMACH',
			'type'                 => 'SOLO',
			'public'               => true,
			'mines'                => true,
			'part_win'             => true,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => true,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => true,
			'player_players'       => true,
			'player_players_teams' => true,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => false,
			'team_score'           => true,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => false,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => true,
			'best_deaths_own'      => true,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => true,
		],
		[
			'id_mode'              => 3,
			'system'               => 'evo5',
			'name'                 => 'CSGO',
			'description'          => 'Náročná hra o přežití se 3mi životy.',
			'load_name'            => '3-TEAM-CSGO',
			'type'                 => 'TEAM',
			'public'               => true,
			'mines'                => false,
			'part_win'             => true,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => false,
			'player_score'         => false,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => false,
			'player_players'       => true,
			'player_players_teams' => false,
			'player_kd'            => false,
			'player_favourites'    => false,
			'player_lives'         => true,
			'team_score'           => false,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => false,
			'best_score'           => false,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => false,
			'best_deaths_own'      => false,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => false,
		],
		[
			'id_mode'              => 4,
			'system'               => 'evo5',
			'name'                 => 'Základny',
			'description'          => 'Strategická hra, kdy 2 týmy bojují proti sobě o zničení základny druhého týmu.',
			'load_name'            => '3-TEAM-Zakladny',
			'type'                 => 'TEAM',
			'public'               => true,
			'mines'                => true,
			'part_win'             => true,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => false,
			'player_score'         => false,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => false,
			'player_players'       => true,
			'player_players_teams' => true,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => false,
			'team_score'           => false,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => true,
			'best_score'           => false,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => true,
			'best_deaths_own'      => true,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => false,
		],
		[
			'id_mode'              => 5,
			'system'               => 'evo5',
			'name'                 => 'Barvičky',
			'description'          => 'Rychlá, šílená hra. Po pár smrtích se přebarvíš na barvu toho, kdo tě trefil.',
			'load_name'            => '3-TEAM-Barvicky',
			'type'                 => 'SOLO',
			'public'               => true,
			'mines'                => false,
			'part_win'             => true,
			'part_teams'           => false,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => false,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => false,
			'player_players'       => true,
			'player_players_teams' => false,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => false,
			'team_score'           => false,
			'team_accuracy'        => false,
			'team_shots'           => false,
			'team_hits'            => false,
			'team_zakladny'        => false,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => false,
			'best_deaths_own'      => false,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => false,
		],
		[
			'id_mode'              => 6,
			'system'               => 'evo5',
			'name'                 => 'T.M.A',
			'description'          => 'Klasická hra, ale tentokrát bez světel.',
			'load_name'            => '3-TEAM-TMA',
			'type'                 => 'TEAM',
			'public'               => true,
			'mines'                => true,
			'part_win'             => false,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => true,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => true,
			'player_players'       => true,
			'player_players_teams' => false,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => false,
			'team_score'           => true,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => false,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => false,
			'best_deaths_own'      => false,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => true,
		],
		[
			'id_mode'              => 7,
			'system'               => 'evo5',
			'name'                 => 'T.M.A - solo',
			'description'          => 'Klasická hra, ale tentokrát bez světel.',
			'load_name'            => '3-SOLO-TMA',
			'type'                 => 'SOLO',
			'public'               => true,
			'mines'                => true,
			'part_win'             => false,
			'part_teams'           => false,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => true,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => true,
			'player_players'       => true,
			'player_players_teams' => false,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => false,
			'team_score'           => false,
			'team_accuracy'        => false,
			'team_shots'           => false,
			'team_hits'            => false,
			'team_zakladny'        => false,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => false,
			'best_deaths_own'      => false,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => true,
		],
		[
			'id_mode'              => 8,
			'system'               => 'evo5',
			'name'                 => 'Apokalypsa',
			'description'          => 'Hra na zombíky! Vybraní hráči jsou zombie, kteří se snaží infikovat ostatní hráče.',
			'load_name'            => '3-TEAM-Apokalypsa',
			'type'                 => 'TEAM',
			'public'               => true,
			'mines'                => false,
			'part_win'             => true,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => true,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => true,
			'player_players'       => true,
			'player_players_teams' => true,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => false,
			'team_score'           => true,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => true,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => false,
			'best_deaths_own'      => false,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => true,
		],
		[
			'id_mode'              => 9,
			'system'               => 'evo5',
			'name'                 => 'Survival',
			'description'          => 'Strategická hra s omezeným počtem životů a nábojů.',
			'load_name'            => '3-SOLO-SURVIVAL',
			'type'                 => 'SOLO',
			'public'               => true,
			'mines'                => false,
			'part_win'             => true,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => true,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => true,
			'player_players'       => true,
			'player_players_teams' => true,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => true,
			'team_score'           => true,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => true,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => false,
			'best_deaths_own'      => false,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => true,
		],
		[
			'id_mode'              => 10,
			'system'               => 'evo5',
			'name'                 => 'Survival',
			'description'          => 'Strategická hra s omezeným počtem životů a nábojů.',
			'load_name'            => '3-TEAM-SURVIVAL',
			'type'                 => 'TEAM',
			'public'               => true,
			'mines'                => false,
			'part_win'             => true,
			'part_teams'           => true,
			'part_players'         => true,
			'part_hits'            => true,
			'part_best'            => true,
			'part_best_day'        => true,
			'player_score'         => true,
			'player_shots'         => true,
			'player_miss'          => true,
			'player_accuracy'      => true,
			'player_mines'         => true,
			'player_players'       => true,
			'player_players_teams' => true,
			'player_kd'            => true,
			'player_favourites'    => true,
			'player_lives'         => true,
			'team_score'           => true,
			'team_accuracy'        => true,
			'team_shots'           => true,
			'team_hits'            => true,
			'team_zakladny'        => true,
			'best_score'           => true,
			'best_hits'            => true,
			'best_deaths'          => true,
			'best_accuracy'        => true,
			'best_hits_own'        => false,
			'best_deaths_own'      => false,
			'best_shots'           => true,
			'best_miss'            => true,
			'best_mines'           => true,
		],
	];

	public const GAME_MODE_NAMES = [
		[
			'id_mode' => 1,
			'sysName' => '1-TEAM',
		],
		[
			'id_mode' => 2,
			'sysName' => '2-SOLO',
		],
		[
			'id_mode' => 3,
			'sysName' => 'CSGO',
		],
		[
			'id_mode' => 4,
			'sysName' => 'Zakladny',
		],
		[
			'id_mode' => 5,
			'sysName' => 'Barvi',
		],
		[
			'id_mode' => 6,
			'sysName' => 'TEAM-TMA',
		],
		[
			'id_mode' => 7,
			'sysName' => 'SOLO-TMA',
		],
		[
			'id_mode' => 8,
			'sysName' => 'Apokalypsa',
		],
		[
			'id_mode' => 9,
			'sysName' => 'SOLO-Survival',
		],
		[
			'id_mode' => 10,
			'sysName' => 'TEAM-Survival',
		],
	];

	public const PRINT_STYLES = [
		[
			'id_style'      => 1,
			'name'          => 'Default',
			'color_dark'    => '#304D99',
			'color_light'   => '#a7d0f0',
			'color_primary' => '#1b4799',
			'bg'            => 'assets/images/print/bg.jpg',
			'default'       => true,
		],
		[
			'id_style'      => 2,
			'name'          => 'Čerti',
			'color_dark'    => '#8d0d04',
			'color_light'   => '#ddaa9b',
			'color_primary' => '#260301',
			'bg'            => 'assets/images/print/bg.jpg',
			'default'       => false,
		],
		[
			'id_style'      => 3,
			'name'          => 'Zima',
			'color_dark'    => '#304d99',
			'color_light'   => '#a7d0f0',
			'color_primary' => '#1b4799',
			'bg'            => 'assets/images/print/bg.jpg',
			'default'       => false,
		],
		[
			'id_style'      => 4,
			'name'          => 'Valentýn',
			'color_dark'    => '#ae202d',
			'color_light'   => '#ddaa9b',
			'color_primary' => '#260301',
			'bg'            => 'assets/images/print/bg.jpg',
			'default'       => false,
		],
		[
			'id_style'      => 5,
			'name'          => 'Vánoce',
			'color_dark'    => '#168740',
			'color_light'   => '#c6f0d2',
			'color_primary' => '#08602c',
			'bg'            => 'assets/images/print/bg.jpg',
			'default'       => false,
		],
		[
			'id_style'      => 6,
			'name'          => 'Nový rok',
			'color_dark'    => '#304D99',
			'color_light'   => '#a7d0f0',
			'color_primary' => '#1b4799',
			'bg'            => 'assets/images/print/bg.jpg',
			'default'       => false,
		],
	];

	public const PRINT_TEMPLATES = [
		[
			'id_template' => 1,
			'slug'        => 'default',
			'name'        => 'Default',
			'description' => 'Basic result template',
		],
	];

	/**
	 * @inheritDoc
	 */
	public static function install(bool $fresh = false) : bool {
		try {
			// Game modes
			if ($fresh) {
				DB::delete(AbstractMode::TABLE, ['1=1']);
			}
			foreach (self::GAME_MODES as $insert) {
				DB::insertIgnore(AbstractMode::TABLE, $insert);
			}
			if ($fresh) {
				DB::delete(AbstractMode::TABLE.'-names', ['1=1']);
			}
			foreach (self::GAME_MODE_NAMES as $insert) {
				DB::insertIgnore(AbstractMode::TABLE.'-names', $insert);
			}

			// Print styles
			if ($fresh) {
				DB::delete(PrintStyle::TABLE.'-names', ['1=1']);
			}
			foreach (self::PRINT_STYLES as $insert) {
				DB::insertIgnore(PrintStyle::TABLE, $insert);
			}

			// Print templates
			if ($fresh) {
				DB::delete(PrintTemplate::TABLE.'-names', ['1=1']);
			}
			foreach (self::PRINT_TEMPLATES as $insert) {
				DB::insertIgnore(PrintTemplate::TABLE, $insert);
			}
		} catch (Exception $e) {
			echo $e->getMessage().PHP_EOL.$e->getSql().PHP_EOL;
			return false;
		}
		return true;
	}
}