version: "3"
services:
  db:
    restart: always
    image: "mariadb:10.6.9"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "laser-arena-control"
      MARIADB_ROOT_PASSWORD: "laser-arena-control"
      MYSQL_DATABASE: "lac"
      MARIADB_DATABASE: "lac"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - backend
  redis:
    restart: always
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    networks:
      - backend
      - frontend
    volumes:
      - redis-data:/data
  eventServer:
    restart: always
    image: heroyt/lac-event-server:latest
    ports:
      - "9999:8080"
    networks:
      - backend
      - frontend
    depends_on:
      - redis
    links:
      - redis
    environment:
      REDIS_HOST: "redis"
  php:
    restart: always
    image: "heroyt/laser-arena-control:nginx-latest"
    working_dir: /var/www/
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - app-data:/var/www
      - lmx:/var/www/lmx
      - ./docker/private:/var/www/private
    networks:
      - backend
  web:
    restart: always
    image: nginx
    depends_on:
      - php
      - db
    ports:
      - "8001:80"
    networks:
      - backend
      - frontend
    links:
      - php
    volumes:
      - app-data:/var/www
      - ./docker/nginx:/etc/nginx
  gotenberg:
    restart: always
    image: gotenberg/gotenberg:7
    networks:
      - backend
    ports:
      - "3000:3000"
volumes:
  redis-data:
  apache-data:
  app-data:
  lmx:
    driver: local
networks:
  backend:
  frontend: