[roadrunner]
ref = "v2025.1.4"

[debug]
enabled = false

[log]
level = "info"
mode = "production"

[github.token]
token = "${RT_TOKEN}"

# LOGS
[github.plugins.appLogger]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "app-logger"

[github.plugins.logger]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "logger"

[github.plugins.lock]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "lock"

[github.plugins.rpc]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "rpc"

# CENTRIFUGE BROADCASTING PLATFORM
[github.plugins.centrifuge]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "centrifuge"

# METRICS
[github.plugins.metrics]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "metrics"

[github.plugins.otel]
ref = "v5.3.1"
owner = "roadrunner-server"
repository = "otel"

# HTTP + MIDDLEWARE
[github.plugins.http]
ref = "v5.2.8"
owner = "roadrunner-server"
repository = "http"

[github.plugins.gzip]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "gzip"

[github.plugins.prometheus]
ref = "v5.1.8"
owner = "roadrunner-server"
repository = "prometheus"

[github.plugins.headers]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "headers"

[github.plugins.static]
ref = "v5.1.7"
owner = "roadrunner-server"
repository = "static"

[github.plugins.proxy]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "proxy_ip_parser"

[github.plugins.send]
ref = "v5.1.6"
owner = "roadrunner-server"
repository = "send"

# SERVER
[github.plugins.server]
ref = "v5.2.10"
owner = "roadrunner-server"
repository = "server"

# SERVICE aka lightweit systemd
[github.plugins.service]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "service"

# JOBS
[github.plugins.jobs]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "jobs"

[github.plugins.amqp]
ref = "v5.2.3"
owner = "roadrunner-server"
repository = "amqp"

# KV
[github.plugins.kv]
ref = "v5.2.9"
owner = "roadrunner-server"
repository = "kv"

[github.plugins.memory]
ref = "v5.2.9"
owner = "roadrunner-server"
repository = "memory"

[github.plugins.redis]
ref = "v5.1.10"
owner = "roadrunner-server"
repository = "redis"

# FILESERVER (static files)
[github.plugins.fileserver]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "fileserver"

# gRPC plugin
[github.plugins.grpc]
ref = "v5.2.3"
owner = "roadrunner-server"
repository = "grpc"

[github.plugins.status]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "status"

[github.plugins.tcp]
ref = "v5.1.9"
owner = "roadrunner-server"
repository = "tcp"

[github.plugins.fileWatch]
ref = "master"
owner = "LaserLiga"
repository = "rr_file_watch"

[github.plugins.eventServer]
ref = "master"
owner = "LaserLiga"
repository = "event_server_rr"