name: Docker Image CI

on:
  push:
    paths:
      - .github/workflows/docker-image.yml
      - docker/Dockerfile
      - docker/DockerfileDev
      - docker/DockerfileDevRR
      - docker/core/*
    branches: [ master ]
  pull_request:
    paths:
      - .github/workflows/docker-image.yml
      - docker/Dockerfile
      - docker/DockerfileDev
      - docker/DockerfileDevRR
      - docker/core/*
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build the Docker image - dev Roadrunner
        run: docker build . --file docker/DockerfileDevRR --tag heroyt/laser-arena-control:dev-latest --tag heroyt/laser-arena-control:dev-roadrunner-latest
      - name: Build the Docker image
        run: docker build . --file docker/Dockerfile --tag heroyt/laser-arena-control:roadrunner-latest
      - name: Push docker images
        run: docker push heroyt/laser-arena-control -a