name: Docker Push on tag

on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@master
            -   name: Publish to Registry
                uses: elgohr/Publish-Docker-Github-Action@v4
                if: contains(github.ref, 'refs/tags/v')
                with:
                    name: heroyt/laser-arena-control
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
                    cache: true
                    tag_names: true
