name: Docker Image CI

on:
    push:
        paths:
            - .github/workflows/docker-image.yml
            - Dockerfile
            - DockerfileDev
            - dockerCore/*
        branches: [ master ]
    pull_request:
        paths:
            - .github/workflows/docker-image.yml
            - Dockerfile
            - DockerfileDev
            - dockerCore/*
        branches: [ master ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   uses: actions/checkout@v2
            -   name: Build the Docker image
                run: docker build . --file DockerfileDev --tag heroyt/laser-arena-control:dev-latest && docker push heroyt/laser-arena-control -a