name: Docker Image Core build

on:
    push:
        paths:
            - docker/core/*
            - .github/workflows/docker-core.yml
        branches: [ master ]
        tags:
            - '*'
    pull_request:
        branches: [ master ]
        paths:
            - docker/core/*

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   uses: actions/checkout@v2
            - name: Build the Docker core image
              run: docker build . --file docker/core/Dockerfile --tag heroyt/lac_core:$(date +%s) --tag heroyt/lac_core:latest --tag heroyt/lac_core:nginx-latest --tag heroyt/lac_core:nginx
            -   name: Push docker image
                run: docker push heroyt/lac_core -a
