name: Docker Push on tag

on:
    push:
        branches: 
            - master
        tags:
            - '*'

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   uses: actions/checkout@v2
            -   name: Build the Docker image
                run: docker build . --file Dockerfile --tag heroyt/laser-arena-control:latest -tag heroyt/laser-arena-control:${GITHUB_REF/refs\/tags\//}
            -   name: Push docker image
                run: docker push heroyt/laser-arena-control -a
