name: Docker Image CI

on:
    push:
        paths:
            - Dockerfile
            - DockerfileDev
            - dockerCore/*
        branches: [ master ]
    pull_request:
        paths:
            - Dockerfile
            - DockerfileDev
            - dockerCore/*
        branches: [ master ]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Build the Docker image
                run: docker build . --file DockerfileDev --tag heroyt/laser-arena-control:dev-latest && docker push -a